var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":143,"id":3386,"methods":[{"el":60,"sc":2,"sl":52},{"el":66,"sc":2,"sl":62},{"el":71,"sc":2,"sl":68},{"el":77,"sc":2,"sl":73},{"el":84,"sc":2,"sl":79},{"el":90,"sc":2,"sl":86},{"el":96,"sc":2,"sl":92},{"el":103,"sc":2,"sl":98},{"el":109,"sc":2,"sl":105},{"el":115,"sc":2,"sl":111},{"el":121,"sc":2,"sl":117},{"el":128,"sc":2,"sl":123},{"el":134,"sc":2,"sl":130},{"el":141,"sc":2,"sl":136}],"name":"JdbcSearchableStepExecutionDaoTests","sl":41}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_117":{"methods":[{"sl":86}],"name":"testFindStepNamesWithMatch","pass":true,"statements":[{"sl":89}]},"test_138":{"methods":[{"sl":130}],"name":"testCountStepExecutionsByPattern","pass":true,"statements":[{"sl":133}]},"test_16":{"methods":[{"sl":98}],"name":"testFindStepExecutionsByNameWithMoreJobs","pass":true,"statements":[{"sl":101},{"sl":102}]},"test_161":{"methods":[{"sl":73}],"name":"testFindStepNames","pass":true,"statements":[{"sl":76}]},"test_170":{"methods":[{"sl":136}],"name":"testCountStepExecutionsByPatternWithMoreJobs","pass":true,"statements":[{"sl":139},{"sl":140}]},"test_181":{"methods":[{"sl":105}],"name":"testFindStepExecutionsByPattern","pass":true,"statements":[{"sl":108}]},"test_216":{"methods":[{"sl":123}],"name":"testCountStepExecutionsByNameWithMoreJobs","pass":true,"statements":[{"sl":126},{"sl":127}]},"test_232":{"methods":[{"sl":79}],"name":"testFindStepNamesWithMoreJobs","pass":true,"statements":[{"sl":82},{"sl":83}]},"test_31":{"methods":[{"sl":92}],"name":"testFindStepExecutionsByName","pass":true,"statements":[{"sl":95}]},"test_49":{"methods":[{"sl":117}],"name":"testCountStepExecutionsByName","pass":true,"statements":[{"sl":120}]},"test_50":{"methods":[{"sl":111}],"name":"testFindStepExecutionsPastEnd","pass":true,"statements":[{"sl":114}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [161], [], [], [161], [], [], [232], [], [], [232], [232], [], [], [117], [], [], [117], [], [], [31], [], [], [31], [], [], [16], [], [], [16], [16], [], [], [181], [], [], [181], [], [], [50], [], [], [50], [], [], [49], [], [], [49], [], [], [216], [], [], [216], [216], [], [], [138], [], [], [138], [], [], [170], [], [], [170], [170], [], [], []]
