var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":248,"id":10994,"methods":[{"el":60,"sc":2,"sl":51},{"el":70,"sc":2,"sl":62},{"el":81,"sc":2,"sl":72},{"el":92,"sc":2,"sl":83},{"el":106,"sc":2,"sl":97},{"el":121,"sc":2,"sl":111},{"el":142,"sc":2,"sl":126},{"el":172,"sc":2,"sl":147},{"el":200,"sc":2,"sl":177},{"el":228,"sc":2,"sl":205}],"name":"SimpleSolrPersistentEntityTests","sl":40},{"el":231,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.SearchableBeanWithSolrDocumentAnnotation","sl":231},{"el":234,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.SearchableBeanWithEmptySolrDocumentAnnotation","sl":234},{"el":236,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.SearchableBeanWithoutSolrDocumentAnnotation","sl":236},{"el":239,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.ParentClassWithSolrDocumentAnnotation","sl":239},{"el":241,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.InheritingClass","sl":241},{"el":244,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.DocumentWithBoost","sl":244},{"el":246,"id":11076,"methods":[],"name":"SimpleSolrPersistentEntityTests.DocumentWithScore","sl":246}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
