var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":211,"id":1685,"methods":[],"name":"DateTimeConverters","sl":47},{"el":71,"id":1685,"methods":[{"el":69,"sc":3,"sl":63}],"name":"DateTimeConverters.JodaDateTimeConverter","sl":60},{"el":84,"id":1691,"methods":[{"el":83,"sc":3,"sl":77}],"name":"DateTimeConverters.StringToJodaDateTimeConverter","sl":74},{"el":103,"id":1697,"methods":[{"el":102,"sc":3,"sl":96}],"name":"DateTimeConverters.DateToJodaDateTimeConverter","sl":93},{"el":124,"id":1703,"methods":[{"el":122,"sc":3,"sl":116}],"name":"DateTimeConverters.JodaDateTimeToDateConverter","sl":113},{"el":145,"id":1709,"methods":[{"el":143,"sc":3,"sl":137}],"name":"DateTimeConverters.JodaLocalDateTimeConverter","sl":134},{"el":166,"id":1715,"methods":[{"el":164,"sc":3,"sl":158}],"name":"DateTimeConverters.JodaLocalDateTimeToDateConverter","sl":155},{"el":187,"id":1721,"methods":[{"el":185,"sc":3,"sl":179}],"name":"DateTimeConverters.DateToLocalDateTimeConverter","sl":176},{"el":209,"id":1727,"methods":[{"el":207,"sc":3,"sl":200}],"name":"DateTimeConverters.JavaDateConverter","sl":197}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
